import google.generativeai as genai


# API kalitni sozlash (faqat bir marta kerak)
genai.configure(api_key="AIzaSyB5AEmYJgFhj04jSPzcAi-C6_eeX6lFRd4")

# Modelni tanlash
model = genai.GenerativeModel(model_name="gemini-1.5-flash")
otabek = "You are an AI text detector. Your task is to analyze the following text and estimate what percentage of it was likely generated by AI and what percentage was written by a human. Output only the percentage of AI-generated content as a number (for example: 75). Do not explain your reasoning, do not write anything else. Here is the text:"
text = """
Sun’iy intellekt: Kelajakning Kaliti

Kirish:
Bugungi kunda texnologiyalar juda tez rivojlanmoqda. Ularning eng katta yutuqlaridan biri bu — sun’iy intellekt (SI) hisoblanadi. Sun’iy intellekt — bu kompyuter va dasturlarni shunday o‘rgatishki, ular odam kabi fikrlay olsin, o‘rganib, qaror qabul qila olsin.

Asosiy qism:
Sun’iy intellekt hayotimizning turli sohalarida keng qo‘llanilmoqda:

- Tibbiyotda: kasalliklarni aniqlash, analiz natijalarini tahlil qilish.
- Transportda: avtopilot tizimlari, yo‘l harakatini boshqarish.
- Ta’limda: avtomatik baholash, o‘quv dasturlarini moslashtirish.
- Sanoatda: zavodlardagi robotlar, avtomatik ishlab chiqarish.

Sun’iy intellektning afzalliklari juda ko‘p. U inson ishini yengillashtiradi, tez va aniq ishlaydi, katta ma’lumotlarni tezda tahlil qiladi. Biroq kamchiliklari ham yo‘q emas. Masalan, ba’zi ish o‘rinlari yo‘qolib ketishi mumkin, shuningdek noto‘g‘ri ishlash xavfi ham mavjud.

Xulosa:
Sun’iy intellekt — bu kelajak texnologiyasi. Agar uni to‘g‘ri va mas’uliyat bilan ishlatsak, hayotimizni osonlashtiradi va ko‘plab muammolarga yechim topishga yordam beradi. Har bir yosh avlod bu sohani o‘rganib, uni foydali maqsadlarda qo‘llashi zarur.
"""


response = model.generate_content(f"{otabek} {text} ")

# Natijani chiqarish
print(response.text)
# Kontent yaratish

